### ISSUE TITLE
Current_Riskfree_Rates.ipynb ModuleNotFoundError: No module named 'pricing'

### ISSUE THREAD

**Issue by veridelisi** [ilchen/US_Economic_Data_Analysis#2]
Hi andrei
in Current_Riskfree_Rates.ipynb

`from pricing import curves, futures_rates`

ModuleNotFoundError: No module named 'pricing'

Sincerely

**Comment by veridelisi** [comment]
User needs to install this and execute python codes in cloned-repo
!git clone -l -s https://github.com/ilchen/US_Economic_Data_Analysis.git cloned-repo
%cd cloned-repo

**Comment by ilchen** [comment]
Thanks a lot for your comments Veri. I updated the README.md to address the points you brought up: https://github.com/ilchen/US_Economic_Data_Analysis/commit/f6f472a6a51e7fead82816e851d28ac4099f5c0d
